modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mombackport"
version = "${version}"
displayName = "MoM Backport"
authors = "zzik2"
description = '''
Backports the Mounts of Mayhem update to 1.21.1
'''
logoFile = "assets/barched/icon.png"

[[dependencies.mombackport]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mombackport]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mombackport]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mombackport]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "barched.mixins.json"

[[mixins]]
config = "barched-neoforge.mixins.json"
